apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-nginx-backend
  labels:
    app: test-nginx-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-nginx-backend
  template:
    metadata:
      labels:
        app: test-nginx-backend
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: test-nginx-service
spec:
  selector:
    app: test-nginx-backend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-nginx-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging # Remove to use existing certificates and not try to autocreate
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - 34.44.159.168.nip.io
      secretName: test-nginx-tls # cert-manager will create this secret, use existing certiticate name if already generated
  rules:
    - host: 34.44.159.168.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: test-nginx-service
                port:
                  number: 80
